# Generated by Django 4.0.6 on 2022-07-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='defcription',
            new_name='description',
        ),
    ]
